### ISSUE TITLE
Publish latest source tarballs on SourceForge

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.arrl.trustedqsl#7]
I know that this is not a problem related to this Flatpak, but I don't know where else to report it.

If possible, please publish the latest (2.7 and 2.7.1) source tarballs [on SourceForge](https://sourceforge.net/projects/trustedqsl/). We use SourceForge for version check for one of our Flatpaks (that bundles TQSL) and it is [also used](https://release-monitoring.org/project/4998/) in some Linux distributions such as Fedora (because of this, Fedora is still at trustedqsl version 2.6.5) or Debian.

**Comment by k1mu** [comment]
Done. Uploaded both.
I've been considering moving off of SourceForge to GitHub. How would such a move impact your usage?
